l4ingress_app3_app3-kafka:
- 10.1.3.51
- 10.1.3.52
- 10.1.3.53
- 10.1.3.54
- 10.1.3.55
- 10.1.3.56
- 10.1.3.59
- 10.1.3.60
l4ingress_app3_app3:
- 10.1.3.57
- 10.1.3.58
l4ingress_app4_app4:
- 10.1.3.61
- 10.1.3.62
